### ISSUE TITLE
Please change LICENSE

### ISSUE THREAD

**Issue by gmacario** [robotrokers/rokers-droidcon-hack#1]
GPLv3 is a red-lighted license in GENIVI.

Please choose one green-lighted license from those in
https://at.projects.genivi.org/wiki/download/attachments/2785433/Public_Policy_for_GENIVI_Licensing_and_Copyright_version_2%200.pdf?api=v2

I have a preference for MPL-2.0 or MIT.

**Comment by gmacario** [comment]
I will **NOT** contribute unless you choose a GENIVI green-lighted license.

**Comment by ludusrusso** [comment]
Solved, I confused BSD3 with GPL3 (3 letters with a 3 at the end are the same for me)!
Sovled in 37695f3!
